import { getGraphBaseUrl, getOAuthDialogUrl, META_OAUTH_SCOPES } from "./config"
import { MetaApiError, readJsonOrThrow, type Fetcher } from "./client"

export type { Fetcher }
export { MetaApiError }

function requireEnv(name: string): string {
  const v = process.env[name]
  if (!v) throw new Error(`${name} is not set`)
  return v
}

/**
 * Build the URL the admin's browser is redirected to in order to begin
 * the Meta OAuth flow. The `state` token is generated by oauth-state.ts
 * and binds this round-trip to a specific clientId.
 */
export function buildAuthUrl(state: string): string {
  const appId = requireEnv("META_APP_ID")
  const redirectUri = requireEnv("META_OAUTH_REDIRECT_URI")
  const params = new URLSearchParams({
    client_id: appId,
    redirect_uri: redirectUri,
    state,
    response_type: "code",
    scope: META_OAUTH_SCOPES.join(","),
  })
  return `${getOAuthDialogUrl()}?${params.toString()}`
}

/**
 * Exchange the OAuth `code` returned to the callback for a short-lived
 * (~1 hour) user access token.
 */
export async function exchangeCodeForToken(
  code: string,
  fetcher: Fetcher = globalThis.fetch
): Promise<{ accessToken: string; tokenType: string; expiresIn?: number }> {
  const appId = requireEnv("META_APP_ID")
  const appSecret = requireEnv("META_APP_SECRET")
  const redirectUri = requireEnv("META_OAUTH_REDIRECT_URI")
  const params = new URLSearchParams({
    client_id: appId,
    client_secret: appSecret,
    redirect_uri: redirectUri,
    code,
  })
  const res = await fetcher(`${getGraphBaseUrl()}/oauth/access_token?${params.toString()}`)
  const body = (await readJsonOrThrow(res)) as {
    access_token?: string
    token_type?: string
    expires_in?: number
  }
  if (!body.access_token) {
    throw new MetaApiError("Graph response is missing access_token", res.status)
  }
  return {
    accessToken: body.access_token,
    tokenType: body.token_type ?? "bearer",
    expiresIn: body.expires_in,
  }
}

/**
 * Swap a short-lived user token for a long-lived (~60 day) user token.
 * A page-scoped token derived from the long-lived user token is
 * effectively non-expiring, which is what we want to persist.
 */
export async function extendUserToken(
  shortLivedToken: string,
  fetcher: Fetcher = globalThis.fetch
): Promise<{ accessToken: string; expiresIn: number }> {
  const appId = requireEnv("META_APP_ID")
  const appSecret = requireEnv("META_APP_SECRET")
  const params = new URLSearchParams({
    grant_type: "fb_exchange_token",
    client_id: appId,
    client_secret: appSecret,
    fb_exchange_token: shortLivedToken,
  })
  const res = await fetcher(`${getGraphBaseUrl()}/oauth/access_token?${params.toString()}`)
  const body = (await readJsonOrThrow(res)) as {
    access_token?: string
    expires_in?: number
  }
  if (!body.access_token) {
    throw new MetaApiError("Graph response is missing access_token", res.status)
  }
  return {
    accessToken: body.access_token,
    expiresIn: body.expires_in ?? 0,
  }
}

export interface MetaPage {
  id: string
  name: string
  accessToken: string
  instagramBusinessId: string | null
}

/**
 * Fetch the user's Facebook Pages via `/me/accounts`, and for each page
 * look up the linked Instagram Business Account id (nullable). Uses each
 * page's own access token for the IG lookup (page-scoped read).
 */
export async function fetchUserPages(
  userAccessToken: string,
  fetcher: Fetcher = globalThis.fetch
): Promise<MetaPage[]> {
  const baseUrl = getGraphBaseUrl()
  const pagesParams = new URLSearchParams({ access_token: userAccessToken })
  const pagesRes = await fetcher(`${baseUrl}/me/accounts?${pagesParams.toString()}`)
  const pagesBody = (await readJsonOrThrow(pagesRes)) as {
    data?: Array<{ id: string; name: string; access_token: string }>
  }
  const rows = pagesBody.data ?? []

  const enriched: MetaPage[] = []
  for (const row of rows) {
    const igParams = new URLSearchParams({
      fields: "instagram_business_account",
      access_token: row.access_token,
    })
    const igRes = await fetcher(`${baseUrl}/${row.id}?${igParams.toString()}`)
    const igBody = (await readJsonOrThrow(igRes)) as {
      instagram_business_account?: { id: string }
    }
    enriched.push({
      id: row.id,
      name: row.name,
      accessToken: row.access_token,
      instagramBusinessId: igBody.instagram_business_account?.id ?? null,
    })
  }
  return enriched
}
